### ISSUE TITLE
[UI] Username too long

### ISSUE THREAD

**Issue by JonahSMS** [JNM-2T17/SECURDE-MP#50]
![asd](https://cloud.githubusercontent.com/assets/9637151/17737275/f1db90a0-64be-11e6-8629-49622076e481.jpg)

Registered with a username exactly 45 characters long. This happened. Send help. =(

**Comment by JonahSMS** [comment]
![asd](https://cloud.githubusercontent.com/assets/9637151/17737374/676ab8fa-64bf-11e6-9466-3fe04dbc210c.jpg)

It gets worse.

**Comment by ryanaustinf** [comment]
=(

**Comment by JonahSMS** [comment]
[https://youtu.be/tOsck7jYUsE?t=56s](url)

**Comment by clar-reese** [comment]
Check if it's okay na :))

**Comment by JonahSMS** [comment]
![asd](https://cloud.githubusercontent.com/assets/9637151/17738746/314c7da2-64c5-11e6-8ca5-5a6ec68bc6a3.jpg)

Is it supposed to look like this?

And did your search break din? Or is it just on my side?

**Comment by clar-reese** [comment]
I pushed something kanina. It should be okay now. I checked in Chrome too this time. :))
